/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import controller.BuscaController;
import model.Usuario;

import javax.swing.*;
/**
 *
 * @author wilso
 */
public class BuscaView extends javax.swing.JFrame {
    private JTextField txtBusca;
    private JButton btnBuscar;
    private JTextArea areaResultado;
    private Usuario usuario;
    /**
     * Creates new form BuscaView
     */
     public BuscaView(Usuario usuario) {
        this.usuario = usuario;

        setTitle("Spotifei - Buscar Musicas");
        setSize(500, 400);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLayout(null);

        JLabel lblBusca = new JLabel("Buscar:");
        lblBusca.setBounds(20, 20, 80, 25);
        add(lblBusca);

        txtBusca = new JTextField();
        txtBusca.setBounds(80, 20, 300, 25);
        add(txtBusca);

        btnBuscar = new JButton("Buscar");
        btnBuscar.setBounds(390, 20, 80, 25);
        add(btnBuscar);

        areaResultado = new JTextArea();
        areaResultado.setEditable(false);
        JScrollPane scroll = new JScrollPane(areaResultado);
        scroll.setBounds(20, 60, 450, 280);
        add(scroll);

        BuscaController controller = new BuscaController(this);
        btnBuscar.addActionListener(e -> controller.buscar());

        // MOSTRAR TODAS AS MÚSICAS AO ABRIR
        controller.buscarTudo();
         JLabel lblIdMusica = new JLabel("ID Musica:");
        lblIdMusica.setBounds(20, 350, 80, 25);
        add(lblIdMusica);

        JTextField txtIdMusica = new JTextField();
        txtIdMusica.setBounds(100, 350, 80, 25);
        add(txtIdMusica);

        JLabel lblIdPlaylist = new JLabel("ID Playlist:");
        lblIdPlaylist.setBounds(200, 350, 80, 25);
        add(lblIdPlaylist);

        JTextField txtIdPlaylist = new JTextField();
        txtIdPlaylist.setBounds(280, 350, 80, 25);
        add(txtIdPlaylist);

        JButton btnAdicionar = new JButton("Adicionar à playlist");
        btnAdicionar.setBounds(370, 350, 80, 25);
        add(btnAdicionar);
        
        JLabel lblCurtir = new JLabel("ID Musica:");
        lblCurtir.setBounds(20, 380, 80, 25);
        add(lblCurtir);

        JTextField txtIdCurtir = new JTextField();
        txtIdCurtir.setBounds(100, 380, 80, 25);
        add(txtIdCurtir);

        JButton btnCurtir = new JButton("Curtir");
        btnCurtir.setBounds(200, 380, 100, 25);
        add(btnCurtir);

        btnCurtir.addActionListener(e -> controller.curtirMusica(txtIdCurtir.getText()));

        btnAdicionar.addActionListener(e -> controller.adicionarAMinhaPlaylist(
            txtIdMusica.getText(),
            txtIdPlaylist.getText()
        ));
        setLocationRelativeTo(null);
        setVisible(true);
    }

    public String getTermoBusca() {
        return txtBusca.getText();
    }

    public void exibirResultados(String texto) {
        areaResultado.setText(texto);
    }

    public Usuario getUsuario() {
        return usuario;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
