/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import controller.PlaylistMusicaController;
import model.Playlist;
import model.Usuario;

import javax.swing.*;
/**
 *
 * @author wilso
 */
public class PlaylistMusicaView extends javax.swing.JFrame {
    private JTextArea areaMusicas;
    private JTextField txtIdMusica;
    private JButton btnRemover;
    private Playlist playlist;
    private Usuario usuario;
    /**
     * Creates new form PlaylistMusicaView
     */
    public PlaylistMusicaView(Playlist playlist) {
        this.playlist = playlist;
        this.usuario = playlist.getUsuario();

        setTitle("Musicas da Playlist: " + playlist.getNome());
        setSize(500, 400);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLayout(null);

        areaMusicas = new JTextArea();
        areaMusicas.setEditable(false);
        JScrollPane scroll = new JScrollPane(areaMusicas);
        scroll.setBounds(20, 20, 440, 250);
        add(scroll);

        JLabel lblId = new JLabel("ID da musica para remover:");
        lblId.setBounds(20, 280, 200, 20);
        add(lblId);

        txtIdMusica = new JTextField();
        txtIdMusica.setBounds(200, 280, 100, 20);
        add(txtIdMusica);

        btnRemover = new JButton("Remover");
        btnRemover.setBounds(320, 280, 100, 25);
        add(btnRemover);

        PlaylistMusicaController controller = new PlaylistMusicaController(this);
        btnRemover.addActionListener(e -> controller.removerMusica());
        controller.carregarMusicas();

        setLocationRelativeTo(null);
        setVisible(true);
    }

    public Playlist getPlaylist() {
        return playlist;
    }

    public int getIdMusicaRemover() {
        try {
            return Integer.parseInt(txtIdMusica.getText());
        } catch (NumberFormatException e) {
            return -1;
        }
    }

    public void exibirMusicas(String texto) {
        areaMusicas.setText(texto);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlaylistMusicaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlaylistMusicaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlaylistMusicaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlaylistMusicaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
