/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import controller.PlaylistController;
import model.Usuario;

import javax.swing.*;/**
 *
 * @author wilso
 */
public class PlaylistView extends JFrame {
    private JTextField txtNome;
    private JTextArea areaPlaylists;
    private JTextField txtId;
    private JButton btnCriar, btnListar, btnAbrir;
    private Usuario usuario;

    public PlaylistView(Usuario usuario) {
        this.usuario = usuario;

        setTitle("Spotifei - Minhas Playlists");
        setSize(500, 400);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLayout(null);

        JLabel lblNome = new JLabel("Nome:");
        lblNome.setBounds(20, 20, 50, 20);
        add(lblNome);

        txtNome = new JTextField();
        txtNome.setBounds(70, 20, 200, 20);
        add(txtNome);

        btnCriar = new JButton("Criar");
        btnCriar.setBounds(280, 20, 80, 20);
        add(btnCriar);

        btnListar = new JButton("Listar");
        btnListar.setBounds(370, 20, 80, 20);
        add(btnListar);

        areaPlaylists = new JTextArea();
        areaPlaylists.setEditable(false);
        JScrollPane scroll = new JScrollPane(areaPlaylists);
        scroll.setBounds(20, 60, 430, 200);
        add(scroll);

        JLabel lblId = new JLabel("ID:");
        lblId.setBounds(20, 280, 30, 20);
        add(lblId);

        txtId = new JTextField();
        txtId.setBounds(50, 280, 50, 20);
        add(txtId);

        btnAbrir = new JButton("Ver musicas");
        btnAbrir.setBounds(120, 280, 120, 25);
        add(btnAbrir);

        PlaylistController controller = new PlaylistController(this);
        btnCriar.addActionListener(e -> controller.criar());
        btnListar.addActionListener(e -> controller.listar());
        btnAbrir.addActionListener(e -> controller.abrirPlaylist());

        // Mostrar todas as playlists ao abrir
        controller.listar();

        setLocationRelativeTo(null);
        setVisible(true);
    }

    public String getNome() {
        return txtNome.getText();
    }

    public int getIdPlaylistSelecionada() {
        try {
            return Integer.parseInt(txtId.getText());
        } catch (NumberFormatException e) {
            return -1;
        }
    }

    public Usuario getUsuario() {
        return usuario;
    }

    public void exibirPlaylists(String texto) {
        areaPlaylists.setText(texto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlaylistView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlaylistView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlaylistView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlaylistView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
